# Generated by Django 5.2 on 2025-06-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unittestgen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="pasted_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testsession",
            name="uploaded_code",
            field=models.FileField(blank=True, null=True, upload_to="uploaded_code/"),
        ),
    ]
