# Generated by Django 5.2 on 2025-11-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unittestgen", "0002_testsession_pasted_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="item_limit",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.CreateModel(
            name="TestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pasted_code", models.TextField(blank=True, null=True)),
                (
                    "uploaded_code",
                    models.FileField(blank=True, null=True, upload_to="uploaded_code/"),
                ),
                ("generated_tests", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="unittestgen.testsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
