# Generated by Django 5.2 on 2025-11-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unittestgen", "0003_testsession_item_limit_testitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="title",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
