# Generated by Django 5.2 on 2025-11-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unittestgen", "0004_testsession_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsession",
            name="title",
            field=models.CharField(blank=True, default="New Session", max_length=120),
        ),
    ]
