# Generated by Django 5.2 on 2025-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unittestgen", "0005_alter_testsession_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsession",
            name="item_limit",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
