# Generated by Django 5.2 on 2025-12-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unittestgen", "0006_alter_testsession_item_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="testitem",
            name="input_method",
            field=models.CharField(
                choices=[("paste", "paste"), ("upload", "upload")],
                default="paste",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="testitem",
            name="source_code",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testitem",
            name="source_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
